[package]
name = "enarx-exec-wasmtime"
version = "0.4.0"
edition = "2021"
description = "Enarx WebAssembly Loader"
authors = ["The Enarx Project Developers"]
repository = "https://github.com/enarx/enarx"
license = "Apache-2.0"

[features]
dbg = []
gdb = []

[dependencies]
anyhow = "1.0"
cap-std = "0.24.2"
clap = { version = "3.1.9", default-features = false, features = ["derive", "std"] }
const-oid = "0.9.0"
env_logger = { version = "0.9", default-features = false }
libc = "0.2.102"
pkcs8 = "0.9.0-pre.1"
ring = { version = "0.16.20", features = ["std"] }
rustix = "0.34.1"
rustls = "0.20.4"
sec1 = "0.3.0-pre.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.2"
toml = "0.5.9"
ureq = { version = "2.4.0" }
url = { version = "2.2.2", features = ["serde"] }
wasi-common = { version = "0.35.2", default-features = false }
wasmtime = { version = "0.35.2", default-features = false, features = ["cranelift", "pooling-allocator"] }
wasmtime-wasi = { version = "0.35.2", default-features = false, features = ["sync"] }
webpki-roots = "0.22.2"
wiggle = { version = "0.35.2", default-features = false }
x509 = { version = "0.0.2", features = ["std"], package = "x509-cert" }
zeroize = { version = "1.5.4", features = ["alloc"] }

[dev-dependencies]
wat = "1.0"
