[package]
name = "enarx-keep-sev-lib"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "Apache-2.0"
edition = "2018"

categories = [
    "no-std",
]

keywords = [
    "no_std",
]

[dependencies]
libc = { version = "0.2.69", features = [] }
memory = { path = "../memory" }
