[toolchain]
channel = "nightly-2022-06-28"
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-unknown-none", "wasm32-wasi"]
profile = "minimal"
components = ["rustfmt", "clippy", "miri", "rust-src"]
