[toolchain]
channel = "nightly-2022-12-14"
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-musl",
    "wasm32-wasi",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-none"
]
profile = "minimal"
components = ["rustfmt", "clippy", "miri", "rust-src"]
