[package]
name = "shim-sgx"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sgx"
test = false

[dependencies]
enarx-heap = { git = "https://github.com/enarx/enarx-heap", rev = "6ecf48aa3db78a0cc17f32870c52446dba30f376" }
sallyport = { git = "https://github.com/enarx/sallyport", features=[ "asm" ], rev="0d3f139366003b196f9c07c437f86d398c73a18c" }
rcrt1 = { git = "https://github.com/enarx/rcrt1", rev = "2205dc7" }
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
sgx = { git = "https://github.com/enarx/sgx", rev = "2f8837a3e27d787ad4d420c588bc54b3ff603402", features = [ "asm" ] }
goblin = { version = "0.4", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.1"
nbytes = "0.1"
lset = "0.1"
xsave = "0.1.1"
const-default = { version = "0.1" }

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
