[package]
name = "shim-sgx"
version = "0.1.0"
authors = ["The Enarx Project Developers"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sgx"
test = false

[dependencies]
sallyport = { git = "https://github.com/enarx/sallyport", rev = "d016f8c6afd50ae2694ddc2d2afea4eec7301a41", features = [ "asm" ] }
sgx = { git = "https://github.com/enarx/sgx", rev = "57df3753a0ea1777963dbf3023452993df2edb8c" }
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
goblin = { version = "0.4", default-features = false, features = [ "elf64" ] }
x86_64 = { version = "^0.14.6", default-features = false }
crt0stack = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
const-default = "0.2"
primordial = "0.3.0"
noted = "^1.0.0"
xsave = "^1.0.0"
flagset = "0.4"
nbytes = "0.1"
rcrt1 = "1.0.0"
lset = "0.2"

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
