[package]
name = "shim-sgx"
version = "0.2.0"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "shim-sgx"
test = false

[features]
gdb = [ "gdbstub", "gdbstub_arch", "dbg" ]
dbg = []

[dependencies]
compiler_builtins = { version = "0.1.68", default-features = false, features = [ "mem" ] }
gdbstub_arch = { version = "0.1.1" , default-features = false, optional = true }
gdbstub = { version = "0.5.0" , default-features = false, optional = true }
goblin = { version = "0.5", default-features = false, features = [ "elf64" ] }
primordial = { version = "^0.4.0", features = ["const-default"] }
x86_64 = { version = "^0.14.8", default-features = false }
crt0stack = { version = "0.1", default-features = false }
sallyport = { version = "0.2.0" }
spinning = { version = "0.1", default-features = false }
libc = { version = "0.2.117", default-features = false }
const-default = "1.0"
noted = "^1.0.0"
xsave = { version = "2.0.2" }
rcrt1 = "1.0.0"
lset = "0.2"
sgx = "0.3"

[dev-dependencies]
memoffset = "0.6.1"

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
