[package]
name = "enarx-shim-sgx"
version = "0.3.0"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "enarx-shim-sgx"
test = false

[features]
gdb = [ "gdbstub", "gdbstub_arch", "dbg" ]
dbg = []
disable-sgx-attestation = []

[dependencies]
gdbstub_arch = { version = "0.2.2" , default-features = false, optional = true }
gdbstub = { version = "0.5.0" , default-features = false, optional = true }
goblin = { version = "0.5", default-features = false, features = [ "elf64" ] }
primordial = { git = "https://github.com/enarx/primordial", rev = "b606b9e472e2238384b003f12fdada077e04d2fe", features = ["const-default"] }
x86_64 = { version = "^0.14.9", default-features = false }
crt0stack = { version = "0.1", default-features = false }
sallyport = { version = "0.3.0", git = "https://github.com/enarx/sallyport", rev = "867b54c50ca43569719b75db22d94199d80268e9" }
spinning = { version = "0.1", default-features = false }
const-default = "1.0"
noted = "^1.0.0"
xsave = { version = "2.0.2" }
rcrt1 = "1.0.0"
lset = { git = "https://github.com/enarx/lset", rev = "5c2feed24d85442725f55d812315854e1b29595d"  }
sgx = { git = "https://github.com/enarx/sgx", rev = "f6de78316cdd74abf825dc3f6794f6f43f744e85" }
mmledger = { git = "https://github.com/enarx/mmledger", rev = "843bd70e5266bcff912d651af0a9c07a413b5626" }

[dev-dependencies]
memoffset = "0.6.1"
