[package]
name = "shim-sev"
version = "0.1.0"
authors = ["The Enarx Project Developers"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sev"
test = false

[dependencies]
sallyport = { git = "https://github.com/enarx/sallyport", rev = "d016f8c6afd50ae2694ddc2d2afea4eec7301a41", features = [ "asm" ] }
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
x86_64 = { version = "^0.14.6", default-features = false, features = ["instructions", "inline_asm"] }
goblin = { version = "0.4", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
spinning = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.3"
xsave = "1.0.0"
noted = "^1.0.0"
nbytes = "0.1"
rcrt1 = "1.0.0"
lset = "0.2"
array-const-fn-init = "0.1"
linked_list_allocator = { version = "0.9.1", default-features = false }
bit_field = "0.10.1"
bitflags = "1.3.2"
lock_api = "0.4.5"
aes-gcm = { version = "0.9.4", features = ["aes"], default-features = false  }
const-default = { version = "0.2", features = [ "derive" ] }
paste = "1.0.5"

[dev-dependencies]
memoffset = "0.6.1"

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
debug = 1
opt-level = "s"
