[package]
name = "shim-sev"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sev"
test = false

[dependencies]
sallyport = { git = "https://github.com/enarx/sallyport", rev = "efccf0f" }
rcrt1 = { git = "https://github.com/enarx/rcrt1", rev = "2205dc7" }
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
x86_64 = { version = "0.13", default-features = false, features = ["instructions", "inline_asm"] }
goblin = { version = "0.3", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
spinning = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.1"
nbytes = "0.1"
lset = "0.1"
array-const-fn-init = "0.1"
linked_list_allocator = { version = "0.9.0", default-features = false }

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
debug = 1
opt-level = "s"
