on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: '15 3 * * 4'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: cargo-update
permissions:
  contents: write
  pull-requests: write  
jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: chore/cargo-update
      - name: Update dependencies
        id: update_dependencies
        run: |
          git config --global init.defaultBranch main
          git config user.name  'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --all
          git reset --hard origin/main
          cargo update --manifest-path=src/bin/shim-kvm/Cargo.toml
          cargo update --manifest-path=src/bin/shim-sgx/Cargo.toml
          cargo update --manifest-path=src/bin/exec-wasmtime/Cargo.toml
          cargo update --manifest-path=Cargo.toml
          git diff --quiet && git diff --staged --quiet || git commit -am 'chore(deps): cargo update to update dependencies' && \
            git push --force origin chore/cargo-update && echo "::set-output name=updated::0"
        shell: bash
      - name: Create pull request
        if: steps.update_dependencies.outputs.updated == 0
        run: |
          gh pr create -B main -b "chore(deps): cargo update to update dependencies" \
                               -t "chore(deps): cargo update to update dependencies" -l dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
