name: coverage

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: ${{ matrix.crate.name }} coverage
    runs-on: ${{ matrix.crate.host }}
    env:
      ENARX_BACKEND: ${{ matrix.crate.name }}

    strategy:
      matrix:
        crate:
          # If you change the number of elements here, also adjust /.codecov.yml
          - name: sev
            path: .
            host: [ self-hosted, linux, sev-snp ]
            flags: --no-default-features --features=backend-sev
          - name: sgx
            path: .
            host: [ self-hosted, linux, sgx ]
            flags: --no-default-features --features=backend-sgx
          - name: kvm
            path: .
            host: [ self-hosted, linux ]
            flags: --no-default-features --features=backend-kvm
          - name: exec-wasmtime
            path: ./crates/exec-wasmtime
            host: ubuntu-20.04 # enarx syscall returns -EPERM on self-hosted (podman??)
          - name: shim-kvm
            path: ./crates/shim-kvm
            host: [ self-hosted, linux ]
          - name: shim-sgx
            path: ./crates/shim-sgx
            host: [ self-hosted, linux ]
          - name: sallyport
            path: ./crates/sallyport
            host: [ self-hosted, linux ]

    steps:
      - run: sudo apt -o Acquire::Retries=3 update
      - run: sudo apt -o Acquire::Retries=3 install -y musl-tools lcov
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: nightly
          profile: minimal
      - name: Setup Rust toolchain
        run: |
          rustup show
          rustup component add llvm-tools-preview

      # Use this special version until https://github.com/haraldh/cargo-llvm-cov/commit/a16a14be4a8f2b522f44eed54231b1022e174906
      # is upstream or in our own enarx repo. It is needed because of our bindeps and enclaves.
      - name: Install cargo-llvm-cov
        run: cargo install --git https://github.com/haraldh/cargo-llvm-cov/ --branch target_rustflags --bin cargo-llvm-cov cargo-llvm-cov

      - name: Run cargo-llvm-cov
        run: cargo llvm-cov ${{ matrix.crate.flags }} --target x86_64-unknown-linux-gnu --manifest-path ${{ matrix.crate.path }}/Cargo.toml --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./
          fail_ci_if_error: false
          files: ./lcov.info
          name: ${{ matrix.crate.name }}
          verbose: true
