name: coverage

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: ${{ matrix.crate.name }} coverage
    runs-on: ${{ matrix.crate.host }}
    env:
      ENARX_BACKEND: ${{ matrix.crate.name }}

    strategy:
      fail-fast: false
      matrix:
        crate:
          # If you change the number of elements here, also adjust /.codecov.yml
          - name: sev
            path: .
            host: [ self-hosted, linux, sev-snp ]
          - name: sgx
            path: .
            host: [ self-hosted, linux, sgx ]
          - name: kvm
            path: .
            host: [ self-hosted, linux, x64 ]
          - name: nil
            path: .
            host: ubuntu-20.04
            flags: "--test integration --bin enarx -- wasm::"
          - name: enarx-config
            path: ./crates/enarx-config
            host: [ self-hosted, linux, x64 ]
          - name: exec-wasmtime
            path: ./crates/exec-wasmtime
            host: [ self-hosted, linux, x64 ]
          - name: shim-kvm
            path: ./crates/shim-kvm
            host: [ self-hosted, linux, sev-snp ]
          - name: shim-sgx
            path: ./crates/shim-sgx
            host: [ self-hosted, linux, sgx ]
          - name: sallyport
            path: ./crates/sallyport
            host: [ self-hosted, linux, x64 ]

    steps:
      - run: sudo apt -o Acquire::Retries=3 update
      - run: sudo apt -o Acquire::Retries=3 install -y musl-tools lcov
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: nightly-2022-06-28
          profile: minimal
      - name: Setup Rust toolchain
        run: |
          rustup show
          rustup component add llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install --version 0.4.1 cargo-llvm-cov

      - name: Run cargo-llvm-cov
        run: cargo llvm-cov --coverage-target-only --target x86_64-unknown-linux-gnu --manifest-path ${{ matrix.crate.path }}/Cargo.toml --lcov --output-path lcov.info ${{ matrix.crate.flags }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./
          fail_ci_if_error: false
          files: ./lcov.info
          name: ${{ matrix.crate.name }}
          verbose: true
