name: test-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: test-docs ${{ matrix.document.name }} ${{ matrix.context.name }} ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt -o Acquire::Retries=3 update
      - run: sudo apt -o Acquire::Retries=3 install -y musl-tools
      - uses: actions/checkout@v3
      - run: helper/md-test.sh --images="${{ matrix.image.name }}" --context="${{ matrix.context.name }}" --document="${{ matrix.document.name }}" --mode="basic"
        shell: bash
      - name: Create issue
        if: ${{ failure() }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '[BUG]: Failure while testing Markdown documentation'
          body: 'There was a failure when testing the documentation. Please review the log from the [failed test-doc action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
          labels: 'bug,documentation'
          assignees: 'nickvidal,bstrie,platten'
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: ubuntu
          - name: debian
          - name: fedora
          - name: centos7
          - name: centos8
        context:
          - name: "git,helloworld"
          - name: "crates,helloworld"
        document:
          - name: "docs/Install.md"
